Crm/Crm/Controllers/RecursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crm.Controllers
{
    public class RecursosController : Controller
    {
        private List<Crm.Models.tbl_paises> Listapaises;
        private List<Crm.Models.tbl_localidad> Listalocalidad;
        // GET : Registro/Paises
        public ActionResult Paises()
        {
            try
            {
                Crm.Models.UsersEntities db = new Models.UsersEntities();

                using (var dbContext = new Models.UsersEntities())
                {
                    var User = (dbContext.tbl_paises);
                    Listapaises = User.AsEnumerable().Select(p => new Crm.Models.tbl_paises
                    {
                        id = p.id,
                        pais = p.pais,
                        estatus = p.estatus
                    }).ToList();


                }
                if (Listapaises != null)
                {
                    return Json(Listapaises, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { err = e.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }
        // GET : Registro/Localidades/0
        public ActionResult Localidades(int id)
        {
            if ( id.ToString() == null) {
                return Json(new { }, JsonRequestBehavior.AllowGet);
            }
            try
            {
                Crm.Models.UsersEntities db = new Models.UsersEntities();

                using (var dbContext = new Models.UsersEntities())
                {
                    var User = (dbContext.tbl_localidad);
                    Listalocalidad = User.AsEnumerable().Where(x => x.idpais ==id).Select(p => new Crm.Models.tbl_localidad
                    {
                        id = p.id,
                        idpais = p.idpais,
                        localidad = p.localidad
                    }).ToList();


                }
                if (Listalocalidad != null)
                {
                    return Json(Listalocalidad, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { err = e.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }
        // GET: Recursos
        public ActionResult Index()
        {
            return View();
        }

        // GET: Recursos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Recursos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Recursos/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recursos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Recursos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recursos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Recursos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Crm/Crm/Controllers/RegistroController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Crm.Controllers
{
    public class RegistroController : Controller
    {
        private List<Crm.Models.usuario> listUser;

        // GET: Registro
        public ActionResult Index()
        {
            try
            {
                using (var dbContext = new Models.UsersEntities())
                {
                    var User = (dbContext.usuarios);
                    listUser = User.AsEnumerable().Select(p => new Crm.Models.usuario
                    {
                        apellido = p.apellido,
                        nombre = p.nombre,
                        rol = p.rol,
                        idusr = p.idusr,
                        usuario1 = p.usuario1
                    }).ToList();


                }
            }
            catch (Exception exception)
            {

                return RedirectToAction("Index");
            }

            return View("Index", listUser);
        }

        // GET: Registro/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Registro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Registro/Save
        [HttpPost]
        public ActionResult Save(FormCollection collection, Crm.Models.usuario usuario)
        {



            try
            {
                Crm.Models.UsersEntities db = new Models.UsersEntities();

                ObjectParameter Output = new ObjectParameter("r", typeof(Int32));

                var clave = this.Encriptar(collection["clave"], "SeguridadMd5Root");

                db.sp_insert_usuario(collection["usuario1"], clave, collection["nombre"], collection["apellido"], Output);
                db.usuarios.Create();

                usuario.LoginErrorMessage = Output.Value.ToString();


            }
            catch (Exception e)
            {
                usuario.LoginErrorMessage = e.Message.ToString();

            }

            return View("Save", usuario);
        }

        // GET: Registro/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Registro/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Registro/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Registro/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // POST: Registro/Participantes
        [HttpPost]
        public ActionResult Participantes(FormCollection collection) {

            var msg = "";
            var success = 0;
            int pais = 0;
            int localidad = 0;
            try
            {
                Crm.Models.UsersEntities db = new Models.UsersEntities();

                ObjectParameter Output = new ObjectParameter("r", typeof(Int32));

                var clave = this.Encriptar(collection["clave"], "SeguridadMd5Root");

                Int32.TryParse(collection["pais"], out pais);
                Int32.TryParse(collection["pais"], out localidad);

                db.sp_registro_participantes(collection["nombre"], collection["apellidos"], collection["dni"], collection["email"], pais, localidad, clave, Output);
                db.usuarios.Create();

                msg = Output.Value.ToString();
                success = 1;

            }
            catch (Exception e)
            {
                msg = e.Message.ToString();
                success = 0;
            }

            return Json(new {success=success,msg=msg });
        }
        private string Encriptar(string pValor, string Key)
        {
            try
            {
                Crm.Controllers.Seguridad obj = new Crm.Controllers.Seguridad();
                return obj.Encriptar(pValor, Key);
            }
            catch (Exception exception)
            {

                return null;
            }
        }
    }
}

Crm/Crm/Views/Shared/_Home.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="icon" href="~/Content/assets/favicon.png" type="image/png">
    <link rel="stylesheet" href="~/Content/assets/css/swiper.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/style.css">
</head>
<body>

    <main class="container">

        <nav id="menu">
            <div class="width">

                <div class="imagen">
                    <img src="~/Content/assets/images/higiene_white.png" alt="">
                </div>

                <div class="options">
                    <div class="item">
                        <a href="" target="_blank">
                            <img src="~/Content/assets/images/facebook.png" alt="">
                        </a>
                    </div>
                    <div class="item lang">
                        <a href="" class="peru">
                            <img src="~/Content/assets/images/lang/peru.png" alt="">
                        </a>

                        <div class="dropdown">
                            <div class="breadcrumb">
                                <span class="these">Estás en:</span>
                                <span class="country">Perú</span>
                            </div>
                            <ul>
                                <!-- <li> -->
                                <!-- <a href=""> -->
                                <!-- <span class="icon master"></span> -->
                                <!-- <span class="name">Master</span> -->
                                <!-- </a> -->
                                <!-- </li> -->
                                <li>
                                    <a href="">
                                        <span class="icon argentina"></span>
                                        <span class="name">Argentina</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <span class="icon colombia"></span>
                                        <span class="name">Colombia</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <span class="icon mexico"></span>
                                        <span class="name">México</span>
                                    </a>
                                </li>
                                <li class="active">
                                    <a href="">
                                        <span class="icon peru"></span>
                                        <span class="name">Perú</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </nav>

        <section id="wrapper">
            <div class="width">
                @RenderBody()
            </div>
        </section>
       
        <footer id="footer">
            <div class="content">
                <div class="width">
                    Para más información acerca de las marcas de Kimberly-Clark, visite el website de Kimberly-Clark Worldwide, Inc. Todos los nombres, logos, marcas y/o propiedad intelectual registrado son propiedad de <br>
                    Kymberly-Clark Worldwide, Inc. y/o sus afiliados. Copyright 2016 Kimberly-Clark Worldwide. Inc. Todos los derechos reservados. Su visita a este sitio y el uso de la información aquí presentada está sujeta a los <br>
                    <a href="#terminos" class="link modaLink">Términos y condiciones contenidos</a> en el aviso de privacidad. Por favor, léala, así como también nuestra <a href="#politicas" class="link modaLink">política de tratamiento de datos personales.</a>
                </div>
            </div>
        </footer>

    </main>


    <script src="~/Content/assets/js/jquery.min.js"></script>
    <script src="~/Content/assets/js/swiper.min.js"></script>
    <script src="~/Content/assets/js/jquery.form.js"></script>
    <script src="~/Content/assets/js/jquery.validate.min.js"></script>
    <script src='https://www.google.com/recaptcha/api.js?hl=es'></script>
    <script src="~/Content/assets/js/jquery.custom.js"></script>

</body>



</html>

Crm/Crm/Views/Shared/_MenuLeft.cshtml
            <!--------------------
           START - Mobile Menu
           -------------------->
            <div class="menu-mobile menu-activated-on-click color-scheme-dark">
                <div class="mm-logo-buttons-w">
                    <a class="mm-logo" href="index.html"><img src="~/Content/img/logo-scott.png"><span>BackOffice Scott</span></a>
                    <div class="mm-buttons">
                        <div class="content-panel-open">
                            <div class="os-icon os-icon-grid-circles"></div>
                        </div>
                        <div class="mobile-menu-trigger">
                            <div class="os-icon os-icon-hamburger-menu-1"></div>
                        </div>
                    </div>
                </div>
                <div class="menu-and-user">
                    <div class="logged-user-w">
                        <div class="avatar-w">
                            <img alt="" src="~/Content/img/avatar1.jpg">
                        </div>
                        <div class="logged-user-info-w">
                            <div class="logged-user-name">
                               @Session["Nombre"]
                            </div>
                            <div class="logged-user-role">
                                @Session["Rol"]
                            </div>
                        </div>
                    </div>
                    <!--------------------
                    START - Mobile Menu List
                    -------------------->
                    <ul class="main-menu">
                        <li class="has-menu">
                            <a href="#">
                                <div class="icon-w">
                                    <div class="os-icon os-icon-window-content"></div>
                                </div>
                                <span>Dashboard</span>
                            </a>

                        </li>
                        <li class="has-sub-menu">
                            <a href="#">
                                <div class="icon-w">
                                    <div class="os-icon os-icon-hierarchy-structure-2"></div>
                                </div>
                                <span>Campañas</span>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="#">Side Menu Light</a>
                                </li>
                                <li>
                                    <a href="#">Side Menu Dark</a>
                                </li>

                            </ul>
                        </li>
                        <li class="has-sub-menu">
                            <a href="#">
                                <div class="icon-w">
                                    <div class="os-icon os-icon-tasks-checked"></div>
                                </div>
                                <span>Resultados</span>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a href="#">Email Application</a>
                                </li>
                                <li>
                                    <a href="#">Support Dashboard <strong class="badge badge-danger">New</strong></a>
                                </li>
                                <li>
                                    <a href="#">Tickets Index <strong class="badge badge-danger">New</strong></a>
                                </li>

                            </ul>
                        </li>
                        <li class="has-sub-menu">
                            <a href="#">
                                <div class="icon-w">
                                    <div class="os-icon os-icon-grid-squares"></div>
                                </div>
                                <span>Opciones</span>
                            </a>
                            <ul class="sub-menu">

                                <li>
                                    <a href="#">Productos</a>
                                </li>
                                <li>
                                    <a href="#">Paises y Ciudades</a>
                                </li>
                            </ul>
                        </li>
                       

                    </ul>
                    <!--------------------
                    END - Mobile Menu List
                    -------------------->

                </div>
            </div>
            <!--------------------
            END - Mobile Menu
            -------------------->
            <!--------------------
            START - Menu side v2
            -------------------->
            <div class="desktop-menu menu-side-v2-w menu-activated-on-hover flying-menu">
                <ul class="main-menu">
                    <li class="menu-sub-header">
                        <span>Herramientas</span>
                    </li>
                    <li class="has-menu">
                        <a href="index.html">
                            <div class="icon-w">
                                <div class="os-icon os-icon-window-content"></div>
                            </div>
                            <span>Dashboard</span>
                        </a>

                    </li>
                    <li class="has-sub-menu">
                        <a href="#">
                            <div class="icon-w">
                                <div class="os-icon os-icon-hierarchy-structure-2"></div>
                            </div>
                            <span>Campañas</span>
                        </a>
                        <div class="sub-menu-w">
                            <div class="sub-menu-header">
                                Campañas
                            </div>
                            <div class="sub-menu-i">
                                <ul class="sub-menu">

                                    <li>
                                        <a href="#">Crear nueva campaña</a>
                                    </li>
                                    <li>
                                        <a href="#">Lista de campañas</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="has-sub-menu">
                        <a href="#">
                            <div class="icon-w">
                                <div class="os-icon os-icon-tasks-checked"></div>
                            </div>
                            <span>Resultados</span>
                        </a>
                        <div class="sub-menu-w">
                            <div class="sub-menu-header">
                                Resultados
                            </div>
                            <div class="sub-menu-i">
                                <ul class="sub-menu">
                                    <li>
                                        <a href="#">Campañas terminadas</a>
                                    </li>
                                    <li>
                                        <a href="#">Partipantes registrados</a>
                                    </li>
                                    <li>
                                        <a href="#">Generar Reportes</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="menu-sub-header">
                        <span>configuración</span>
                    </li>
                    <li class="has-sub-menu">
                        <a href="#">
                            <div class="icon-w">
                                <div class="os-icon os-icon-grid-squares"></div>
                            </div>
                            <span>Opciones</span>
                        </a>
                        <div class="sub-menu-w">
                            <div class="sub-menu-header">
                                Opciones
                            </div>
                            <div class="sub-menu-i">
                                <ul class="sub-menu">
                                    <li>
                                        <a href="#">Paises y ciudades</a>
                                    </li>
                                    <li>
                                        <a href="#">Reporte de accesos</a>
                                    </li>
                                    <li>
                                        <a href="#">Políticas de Uso</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="has-sub-menu">
                        <a href="#">
                            <div class="icon-w">
                                <div class="os-icon os-icon-user-male-circle"></div>
                            </div>
                            <span>Usuarios</span>
                        </a>
                        <div class="sub-menu-w">
                            <div class="sub-menu-header">
                                Usuarios
                            </div>
                            <div class="sub-menu-i">
                                <ul class="sub-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Registro")">Lista de usuarios</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Create", "Registro")">Registrar usuarios</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
                <div class="side-menu-magic">
                    <h4>
                       Campañas KCC
                    </h4>
                    <p>
                        Crea, personaliza y pública tu campaña de marketing
                    </p>
                    <div class="btn-w">
                        <a class="btn btn-white btn-rounded" href="#" target="_blank">CREAR AHORA</a>
                    </div>
                </div>
            </div>
            <!--------------------
            END - Menu side v2
            -------------------->

Crm/Crm/Views/Shared/_PublicLogin.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="icon" href="~/Content/assets/favicon.png" type="image/png">
    <link rel="stylesheet" href="~/Content/assets/css/swiper.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/style.css">
</head>
<body>

    <main class="container">

        <nav id="menu">
            <div class="width">

                <div class="imagen">
                    <img src="~/Content/assets/images/higiene_white.png" alt="">
                </div>

                <div class="options">
                    <div class="item">
                        <a href="" target="_blank">
                            <img src="~/Content/assets/images/facebook.png" alt="">
                        </a>
                    </div>
                    <div class="item lang">
                        <a href="" class="peru">
                            <img src="~/Content/assets/images/lang/peru.png" alt="">
                        </a>

                        <div class="dropdown">
                            <div class="breadcrumb">
                                <span class="these">Estás en:</span>
                                <span class="country">Perú</span>
                            </div>
                            <ul>
                                <!-- <li> -->
                                <!-- <a href=""> -->
                                <!-- <span class="icon master"></span> -->
                                <!-- <span class="name">Master</span> -->
                                <!-- </a> -->
                                <!-- </li> -->
                                <li>
                                    <a href="">
                                        <span class="icon argentina"></span>
                                        <span class="name">Argentina</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <span class="icon colombia"></span>
                                        <span class="name">Colombia</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        <span class="icon mexico"></span>
                                        <span class="name">México</span>
                                    </a>
                                </li>
                                <li class="active">
                                    <a href="">
                                        <span class="icon peru"></span>
                                        <span class="name">Perú</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </nav>

        <section id="wrapper">
            <div class="width">
                @RenderBody()
            </div>
        </section>

        <footer id="footer">
            <div class="content">
                <div class="width">
                    Para más información acerca de las marcas de Kimberly-Clark, visite el website de Kimberly-Clark Worldwide, Inc. Todos los nombres, logos, marcas y/o propiedad intelectual registrado son propiedad de <br>
                    Kymberly-Clark Worldwide, Inc. y/o sus afiliados. Copyright 2016 Kimberly-Clark Worldwide. Inc. Todos los derechos reservados. Su visita a este sitio y el uso de la información aquí presentada está sujeta a los <br>
                    <a href="#terminos" class="link modaLink">Términos y condiciones contenidos</a> en el aviso de privacidad. Por favor, léala, así como también nuestra <a href="#politicas" class="link modaLink">política de tratamiento de datos personales.</a>
                </div>
            </div>
        </footer>

    </main>


    <script src="~/Content/assets/js/jquery.min.js"></script>
    <script src="~/Content/assets/js/swiper.min.js"></script>
    <script src="~/Content/assets/js/jquery.form.js"></script>
    <script src="~/Content/assets/js/jquery.validate.min.js"></script>
    <script src='https://www.google.com/recaptcha/api.js?hl=es'></script>
    <script src="~/Content/assets/js/jquery.custom.js"></script>
    <script>
        $(document).ready(function () {

            $.get('@Url.Action("Paises", "Recursos")', function (data) {

                var html = '<option value="">País</option>';

                var htmlselect = '<option value="">Localidad</option>';

                if ($.trim(data) !== "") {
                    $.each(data, function (o, p) {
                        html += '<option value="' + p.id + '">' + p.pais + '</option>';
                    });

                    $("#pais").html(html);
                    $("#pais").change(function () {
                        $.get('@Url.Action("Localidades", "Recursos")' + '/' + $(this).val(), function (data) {
                            if ($.trim(data) !== "") {
                                $.each(data, function (o, p) {
                                    htmlselect += '<option value="' + p.id + '">' + p.localidad + '</option>';
                                });
                                $("#localidad").html(htmlselect);
                            }
                        }, 'json');
                    });
                }

            }, 'json');


        });
    </script>

</body>



</html>